runtime: java
env: flex
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
service: zipcodes

handlers:
  - url: /.*
    script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 3.2
  disk_size_gb: 20
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1.5